"""
Stratified Farthest Point Sampling for active-learning selection.

The candidate pool generated by Section 2.2 contains configurations from
five different sources (escape_md, relaxation, minimum, walk_accepted,
walk_rejected) which occupy distinct regions of descriptor space. A naive
global FPS would be dominated by whichever source is most spread out
(typically escape_md). We instead allocate a per-source quota and run FPS
independently within each source.

Reference: Section 2.3 of the manuscript, Eq. (3).
"""

from __future__ import annotations

from typing import Optional

import numpy as np


# Default per-source weights (must sum to 1.0)
DEFAULT_SOURCE_WEIGHTS = {
    "minimum":        0.25,
    "walk_accepted":  0.35,
    "escape_md":      0.20,
    "relaxation":     0.10,
    "walk_rejected":  0.10,
}


def _fps_single_pool(
    features: np.ndarray,
    n_select: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """
    Run Farthest Point Sampling on a single feature pool.

    Parameters
    ----------
    features : (N, D) array
    n_select : int, target number to select
    rng : np.random.Generator

    Returns
    -------
    selected_indices : (n_select,) array of int indices into `features`.

    Notes
    -----
    Uses standard greedy max-min algorithm:
        1. Pick first point randomly.
        2. For each subsequent step, pick the point that maximizes its
           minimum distance to the already-selected set.
    Time complexity: O(N * n_select). Memory: O(N) for distance vector.
    """
    n_total = len(features)
    if n_select >= n_total:
        return np.arange(n_total)

    selected = np.zeros(n_select, dtype=np.int64)
    # Distance from each point to the currently selected set; start with
    # +infinity so the first selection is unrestricted.
    min_dist_to_selected = np.full(n_total, np.inf, dtype=np.float64)

    # Step 1: random first point
    first = int(rng.integers(n_total))
    selected[0] = first

    # Update distances after first selection
    diff = features - features[first]
    sq = (diff * diff).sum(axis=-1)
    np.minimum(min_dist_to_selected, sq, out=min_dist_to_selected)

    # Step 2+: greedy max-min
    for k in range(1, n_select):
        next_idx = int(np.argmax(min_dist_to_selected))
        selected[k] = next_idx
        # Update distances: each point's min distance might decrease after
        # the new point is added
        diff = features - features[next_idx]
        sq = (diff * diff).sum(axis=-1)
        np.minimum(min_dist_to_selected, sq, out=min_dist_to_selected)
        # Mark already-selected points so they're never chosen again
        min_dist_to_selected[next_idx] = -np.inf

    return selected


def stratified_fps_selection(
    features: np.ndarray,
    source_tags: list[str],
    n_select_total: int,
    source_weights: Optional[dict[str, float]] = None,
    seed: int = 0,
    verbose: bool = True,
) -> dict:
    """
    Per-source stratified Farthest Point Sampling.

    Parameters
    ----------
    features : (N, D) array
        Reduced (KPCA-space) descriptors of the candidate pool.
    source_tags : list of str of length N
        Source tag for each row in `features`.
    n_select_total : int
        Total number to select across all sources.
    source_weights : dict, optional
        Weights for per-source allocation. Must sum to 1.0. If None,
        uses DEFAULT_SOURCE_WEIGHTS.
    seed : int
        Random seed for reproducibility.
    verbose : bool

    Returns
    -------
    result : dict with keys:
        "selected_indices"      : np.ndarray, indices into the input features
        "selected_source_tags"  : list of str, source tag of each selection
        "per_source_counts"     : dict, actual number selected per source
        "per_source_quotas"     : dict, target quotas per source
        "weights_used"          : dict, weights used for allocation
    """
    if source_weights is None:
        source_weights = DEFAULT_SOURCE_WEIGHTS

    # Normalize weights in case they don't sum to 1
    total_w = sum(source_weights.values())
    if abs(total_w - 1.0) > 1e-6:
        if verbose:
            print(f"[FPS] normalizing weights (sum was {total_w:.4f})")
        source_weights = {k: v / total_w for k, v in source_weights.items()}

    features = np.asarray(features)
    source_tags = list(source_tags)
    assert len(features) == len(source_tags), \
        f"features ({len(features)}) and source_tags ({len(source_tags)}) length mismatch"

    rng = np.random.default_rng(seed)

    # Group indices by source
    source_to_indices: dict[str, list[int]] = {}
    for i, tag in enumerate(source_tags):
        source_to_indices.setdefault(tag, []).append(i)

    # Compute per-source quotas (using ceiling)
    quotas: dict[str, int] = {}
    for tag, w in source_weights.items():
        quotas[tag] = int(np.ceil(w * n_select_total))

    # Run FPS within each source
    all_selected: list[int] = []
    actual_counts: dict[str, int] = {}

    if verbose:
        print(f"[FPS] selecting {n_select_total} total from "
              f"{len(features)} candidates across "
              f"{len(source_to_indices)} sources")

    for tag, indices in source_to_indices.items():
        if tag not in quotas:
            if verbose:
                print(f"[FPS]   warning: source '{tag}' not in weights, skipping "
                      f"({len(indices)} configurations)")
            continue
        target = quotas[tag]
        available = len(indices)
        actual = min(target, available)
        if available == 0:
            actual_counts[tag] = 0
            continue
        sub_features = features[indices]
        local_selected = _fps_single_pool(sub_features, actual, rng)
        global_selected = [indices[i] for i in local_selected]
        all_selected.extend(global_selected)
        actual_counts[tag] = actual
        if verbose:
            print(f"[FPS]   source='{tag}': "
                  f"target={target}, available={available}, selected={actual}")

    # Truncate if we overshoot due to ceiling-rounding
    if len(all_selected) > n_select_total:
        # Drop the last few selections (random source has the slack)
        all_selected = all_selected[:n_select_total]
        if verbose:
            print(f"[FPS] truncated to exact target {n_select_total}")

    selected_indices = np.array(all_selected, dtype=np.int64)
    selected_tags = [source_tags[i] for i in selected_indices]

    result = {
        "selected_indices": selected_indices,
        "selected_source_tags": selected_tags,
        "per_source_counts": actual_counts,
        "per_source_quotas": quotas,
        "weights_used": source_weights,
    }

    if verbose:
        print(f"[FPS] done. total selected = {len(selected_indices)}")

    return result